spring:
  application:
    name: employee-service  # Имя приложения для идентификации в config server
  cloud:
    config:
      uri: http://localhost:8888  # Адрес конфиг-сервера
      name: employee-service     # Имя конфигурации, которую мы хотим загрузить
      profile: default           # Профиль конфигурации (если нужно)
      label: master              # Ветка, из которой загружать конфигурации
  datasource:
    url: jdbc:postgresql://localhost:5455/employee_db  # Параметры подключения к базе
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true  # Включить Liquibase
    change-log: classpath:/db/changelog/db.changelog-master.xml  # Путь к changelog

