server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  topic-name: users-topic
