server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-consumer-group
      auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://localhost:5435/users
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  topic-name: users-topic
